# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_3.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1088, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.wyChooseFile = QtWidgets.QPushButton(self.centralwidget)
        self.wyChooseFile.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/img/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.wyChooseFile.setIcon(icon)
        self.wyChooseFile.setIconSize(QtCore.QSize(30, 30))
        self.wyChooseFile.setAutoDefault(False)
        self.wyChooseFile.setObjectName("wyChooseFile")
        self.horizontalLayout_5.addWidget(self.wyChooseFile)
        self.wyShowArchitecture = QtWidgets.QPushButton(self.centralwidget)
        self.wyShowArchitecture.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/img/biology.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wyShowArchitecture.setIcon(icon1)
        self.wyShowArchitecture.setIconSize(QtCore.QSize(30, 30))
        self.wyShowArchitecture.setObjectName("wyShowArchitecture")
        self.horizontalLayout_5.addWidget(self.wyShowArchitecture)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/img/funnel.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.radioButton.setIcon(icon2)
        self.radioButton.setIconSize(QtCore.QSize(30, 30))
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pic/img/layers.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.radioButton_2.setIcon(icon3)
        self.radioButton_2.setIconSize(QtCore.QSize(30, 30))
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setObjectName("listView")
        self.verticalLayout_3.addWidget(self.listView)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.wyPlot = QtWidgets.QPushButton(self.centralwidget)
        self.wyPlot.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pic/img/brush.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.wyPlot.setIcon(icon4)
        self.wyPlot.setIconSize(QtCore.QSize(30, 30))
        self.wyPlot.setObjectName("wyPlot")
        self.verticalLayout_2.addWidget(self.wyPlot)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelPatch_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPatch_2.sizePolicy().hasHeightForWidth())
        self.labelPatch_2.setSizePolicy(sizePolicy)
        self.labelPatch_2.setMaximumSize(QtCore.QSize(30, 30))
        self.labelPatch_2.setText("")
        self.labelPatch_2.setTextFormat(QtCore.Qt.AutoText)
        self.labelPatch_2.setPixmap(QtGui.QPixmap(":/pic/img/alpha.png"))
        self.labelPatch_2.setScaledContents(True)
        self.labelPatch_2.setObjectName("labelPatch_2")
        self.horizontalLayout_7.addWidget(self.labelPatch_2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_7.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelPatch_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPatch_3.sizePolicy().hasHeightForWidth())
        self.labelPatch_3.setSizePolicy(sizePolicy)
        self.labelPatch_3.setMaximumSize(QtCore.QSize(30, 30))
        self.labelPatch_3.setText("")
        self.labelPatch_3.setTextFormat(QtCore.Qt.AutoText)
        self.labelPatch_3.setPixmap(QtGui.QPixmap(":/pic/img/gamma.png"))
        self.labelPatch_3.setScaledContents(True)
        self.labelPatch_3.setObjectName("labelPatch_3")
        self.horizontalLayout_8.addWidget(self.labelPatch_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_8.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/pic/img/one.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_3.setIcon(icon5)
        self.radioButton_3.setIconSize(QtCore.QSize(30, 30))
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_9.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/pic/img/two.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_4.setIcon(icon6)
        self.radioButton_4.setIconSize(QtCore.QSize(30, 30))
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_9.addWidget(self.radioButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.wySubsetSelection = QtWidgets.QPushButton(self.centralwidget)
        self.wySubsetSelection.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/pic/img/microscope.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.wySubsetSelection.setIcon(icon7)
        self.wySubsetSelection.setIconSize(QtCore.QSize(30, 30))
        self.wySubsetSelection.setObjectName("wySubsetSelection")
        self.verticalLayout_2.addWidget(self.wySubsetSelection)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 262, 733))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.addWidget(self.scrollArea)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.matplotlibwidget_static = MatplotlibWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matplotlibwidget_static.sizePolicy().hasHeightForWidth())
        self.matplotlibwidget_static.setSizePolicy(sizePolicy)
        self.matplotlibwidget_static.setObjectName("matplotlibwidget_static")
        self.verticalLayout_4.addWidget(self.matplotlibwidget_static)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelPatch = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPatch.sizePolicy().hasHeightForWidth())
        self.labelPatch.setSizePolicy(sizePolicy)
        self.labelPatch.setMaximumSize(QtCore.QSize(30, 30))
        self.labelPatch.setText("")
        self.labelPatch.setTextFormat(QtCore.Qt.AutoText)
        self.labelPatch.setPixmap(QtGui.QPixmap(":/pic/img/input.png"))
        self.labelPatch.setScaledContents(True)
        self.labelPatch.setObjectName("labelPatch")
        self.horizontalLayout_2.addWidget(self.labelPatch)
        self.horizontalSliderPatch = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSliderPatch.sizePolicy().hasHeightForWidth())
        self.horizontalSliderPatch.setSizePolicy(sizePolicy)
        self.horizontalSliderPatch.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPatch.setObjectName("horizontalSliderPatch")
        self.horizontalLayout_2.addWidget(self.horizontalSliderPatch)
        self.lcdNumberPatch = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberPatch.sizePolicy().hasHeightForWidth())
        self.lcdNumberPatch.setSizePolicy(sizePolicy)
        self.lcdNumberPatch.setObjectName("lcdNumberPatch")
        self.horizontalLayout_2.addWidget(self.lcdNumberPatch)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelSlice = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSlice.sizePolicy().hasHeightForWidth())
        self.labelSlice.setSizePolicy(sizePolicy)
        self.labelSlice.setMaximumSize(QtCore.QSize(30, 29))
        self.labelSlice.setText("")
        self.labelSlice.setPixmap(QtGui.QPixmap(":/pic/img/research.png"))
        self.labelSlice.setScaledContents(True)
        self.labelSlice.setObjectName("labelSlice")
        self.horizontalLayout_3.addWidget(self.labelSlice)
        self.horizontalSliderSlice = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSliderSlice.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderSlice.setObjectName("horizontalSliderSlice")
        self.horizontalLayout_3.addWidget(self.horizontalSliderSlice)
        self.lcdNumberSlice = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberSlice.sizePolicy().hasHeightForWidth())
        self.lcdNumberSlice.setSizePolicy(sizePolicy)
        self.lcdNumberSlice.setObjectName("lcdNumberSlice")
        self.horizontalLayout_3.addWidget(self.lcdNumberSlice)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 5)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1088, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setText(_translate("MainWindow", "0.0000001"))
        self.lineEdit_2.setText(_translate("MainWindow", "0.19"))

from test import MatplotlibWidget
import img_rc
