# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1088, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.matplotlibwidget_static = MatplotlibWidget(self.centralwidget)
        self.matplotlibwidget_static.setGeometry(QtCore.QRect(480, 30, 601, 681))
        self.matplotlibwidget_static.setObjectName("matplotlibwidget_static")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 141, 281))
        self.groupBox.setObjectName("groupBox")
        self.listView = QtWidgets.QListView(self.groupBox)
        self.listView.setGeometry(QtCore.QRect(10, 60, 121, 171))
        self.listView.setObjectName("listView")
        self.wyPlot = QtWidgets.QPushButton(self.groupBox)
        self.wyPlot.setGeometry(QtCore.QRect(50, 240, 40, 40))
        self.wyPlot.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/img/brush.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.wyPlot.setIcon(icon)
        self.wyPlot.setIconSize(QtCore.QSize(30, 30))
        self.wyPlot.setObjectName("wyPlot")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 20, 122, 36))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/img/funnel.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.radioButton.setIcon(icon1)
        self.radioButton.setIconSize(QtCore.QSize(30, 30))
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/img/layers.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.radioButton_2.setIcon(icon2)
        self.radioButton_2.setIconSize(QtCore.QSize(30, 30))
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.matplotlibwidget_static_2 = MatplotlibWidget(self.centralwidget)
        self.matplotlibwidget_static_2.setGeometry(QtCore.QRect(270, 20, 781, 571))
        self.matplotlibwidget_static_2.setObjectName("matplotlibwidget_static_2")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(480, 720, 521, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(1010, 720, 71, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(210, 10, 241, 701))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 239, 699))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.wyChooseFile = QtWidgets.QPushButton(self.centralwidget)
        self.wyChooseFile.setGeometry(QtCore.QRect(40, 10, 40, 40))
        self.wyChooseFile.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pic/img/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.wyChooseFile.setIcon(icon3)
        self.wyChooseFile.setIconSize(QtCore.QSize(30, 30))
        self.wyChooseFile.setAutoDefault(False)
        self.wyChooseFile.setObjectName("wyChooseFile")
        self.wyShowArchitecture = QtWidgets.QPushButton(self.centralwidget)
        self.wyShowArchitecture.setGeometry(QtCore.QRect(100, 10, 40, 40))
        self.wyShowArchitecture.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pic/img/biology.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wyShowArchitecture.setIcon(icon4)
        self.wyShowArchitecture.setIconSize(QtCore.QSize(30, 30))
        self.wyShowArchitecture.setObjectName("wyShowArchitecture")
        self.wySubsetSelection = QtWidgets.QPushButton(self.centralwidget)
        self.wySubsetSelection.setGeometry(QtCore.QRect(70, 350, 40, 40))
        self.wySubsetSelection.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/pic/img/microscope.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.wySubsetSelection.setIcon(icon5)
        self.wySubsetSelection.setIconSize(QtCore.QSize(30, 30))
        self.wySubsetSelection.setObjectName("wySubsetSelection")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1088, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Architecture"))

from test import MatplotlibWidget
import img_rc
